server:
  port: 8771
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
  redis:
      database: 0
      host: 39.106.215.155
      port: 6379
      timeout: 2000


product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true
    command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 4000
client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
